"""Fixture-hygiene provenance guard.

Per suggestions/feedback.md Addendum #3 (second-pass findings): sentinel
fixtures must be generated by `sentinel record` on real hardware and labeled
with hardware provenance — never hand-written. This test enforces that
discipline by scanning every file under tests/_fixtures/ (other than
.gitkeep) for a `# recorded-on:` provenance header.

Provenance header format:
    # recorded-on: <gpu-type> <iso-date>
    # model: <model-id>
    # git-sha: <short-sha>

Reference: .planning/addendums/README.md (Gap C from 2026-07-09 audit).
"""

from __future__ import annotations

import re
from pathlib import Path

FIXTURE_DIR = Path(__file__).parent / "_fixtures"
GITKEEP_NAME = ".gitkeep"
PROVENANCE_PATTERN = re.compile(r"^#\s*recorded-on:\s*\S+.*\d{4}-\d{2}-\d{2}", re.MULTILINE)


def _non_gitkeep_fixtures() -> list[Path]:
    """Return every file under tests/_fixtures/ except .gitkeep."""
    if not FIXTURE_DIR.exists():
        return []
    return [p for p in FIXTURE_DIR.iterdir() if p.is_file() and p.name != GITKEEP_NAME]


def test_no_hand_written_fixtures_present() -> None:
    """No fixture file may exist without a recorded-on provenance header.

    Fail-closed: any fixture without provenance header is rejected so that
    CI surfaces hand-edited fixtures before they ship. If no fixtures are
    present yet (sentinel never run on real hardware), the test passes —
    there's nothing to violate.
    """
    fixtures = _non_gitkeep_fixtures()
    if not fixtures:
        return  # sentinel has not yet produced fixtures on real hardware
    missing = [p.name for p in fixtures if not PROVENANCE_PATTERN.search(p.read_text())]
    assert not missing, (
        f"fixtures missing '# recorded-on:' provenance header: {missing}. "
        "Regenerate via `python3 tests/sentinel.py --mode record "
        "--base-url http://localhost:18000/v1` on trusted hardware."
    )


def test_gitkeep_present() -> None:
    """The .gitkeep placeholder must remain so the directory is tracked."""
    assert (FIXTURE_DIR / GITKEEP_NAME).exists(), (
        f"{GITKEEP_NAME} missing from tests/_fixtures/ — directory will not be tracked"
    )


def test_gitkeep_carries_no_provenance_header() -> None:
    """.gitkeep is a placeholder, not a recorded fixture — no provenance needed."""
    text = (FIXTURE_DIR / GITKEEP_NAME).read_text()
    assert not PROVENANCE_PATTERN.search(text), (
        ".gitkeep is a placeholder; provenance headers belong on real recorded fixtures only"
    )